version: "3.8"

services:
  smarttransit_api:
    build:
      context: .
      dockerfile: SmartTransit.Application/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    networks:
      - SmartTransit_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - SmartTransit_network

networks:
  SmartTransit_network:
    driver: bridge

volumes:
  mysql_data:
